export interface Character {
  id: number;
  school: string;
  mascot: string;
  nickname: string;
  hometown: string;
  race?: string;
  byline?: string;
  major?: string;
  upgradePath?: string;
}

export const characters: Character[] = [
  {
    id: 150,
    school: "Duke",
    mascot: "Blue Devils",
    nickname: "Cook",
    hometown: "Oxford, NC",
    race: "White",
    byline:
      "Has the sought the help of occult groups to improve basketball and fighting skills",
  },
  {
    id: 248,
    school: "Houston",
    mascot: "Cougars",
    nickname: "Mo",
    hometown: "Missouri City, Texas",
    race: "Black",
    byline: "Engineer and car enthusiast",
  },
  {
    id: 2,
    school: "Auburn",
    mascot: "Tigers",
    nickname: "Tomber",
    hometown: "Selma, AL",
    race: "Black",
  },
  {
    id: 57,
    school: "Florida",
    mascot: "Gators",
    nickname: "Zip",
    hometown: "Hawthorne, FL",
    race: "White",
    byline: "Hails from Florida swamp country. Wrestles alligators for fun.",
  },
  {
    id: 333,
    school: "Alabama",
    mascot: "Crimson Tide",
    nickname: "Bloodhound",
    hometown: "Hawthorne, FL",
    race: "White",
    major: "Bioengineering",
    byline: "Grey up with Zip in swamp country florida",
  },
  {
    id: 2599,
    school: "St. John's",
    mascot: "Red Storm",
    nickname: "Cole",
    hometown: "Glen Cove, NY",
    race: "Black",
    byline: "Studying meteorology",
  },
  {
    id: 127,
    school: "Michigan St.",
    mascot: "Spartans",
    nickname: "Leo",
    hometown: "Grand Ledge, MI",
    race: "White",
    major: "Ancient History",
  },
  {
    id: 2633,
    school: "Tennessee",
    mascot: "Volunteers",
    nickname: "Mountain Man",
    hometown: "Dandridge, TN",
    race: "White",
  },
  {
    id: 2641,
    school: "Texas Tech",
    mascot: "Red Raiders",
    nickname: "Dust Devil",
    hometown: "Post, TX",
  },
  {
    id: 228,
    school: "Clemson",
    mascot: "Tigers",
    nickname: "Palmetto",
    hometown: "Pendleton, SC",
  },
  {
    id: 120,
    school: "Maryland",
    mascot: "Terrapins",
    nickname: "Shell Scholar",
    hometown: "Ellicott City, MD",
    major: "Zoology",
  },
  {
    id: 66,
    school: "Iowa St.",
    mascot: "Cyclones",
    nickname: "Storm Chaser",
    hometown: "Nevada, IA",
    major: "Meteorology",
  },
  {
    id: 97,
    school: "Louisville",
    mascot: "Cardinals",
    nickname: "Derby King",
    hometown: "La Grange, KY",
  },
  {
    id: 245,
    school: "Texas A&M",
    mascot: "Aggies",
    nickname: "Farmhand",
    hometown: "Navasota, TX",
  },
  {
    id: 96,
    school: "Kentucky",
    mascot: "Wildcats",
    nickname: "Bluegrass",
    hometown: "Midway, KY",
  },
  {
    id: 235,
    school: "Memphis",
    mascot: "Tigers",
    nickname: "Blues",
    hometown: "Germantown, TN",
  },
  {
    id: 252,
    school: "BYU",
    mascot: "Cougars",
    nickname: "Mountain Saint",
    hometown: "Springville, UT",
  },
  {
    id: 275,
    school: "Wisconsin",
    mascot: "Badgers",
    nickname: "Cheese",
    hometown: "Mount Horeb, WI",
  },
  {
    id: 2608,
    school: "Saint Mary's",
    mascot: "Gaels",
    nickname: "Gold Rush",
    hometown: "Martinez, CA",
  },
  {
    id: 2509,
    school: "Purdue",
    mascot: "Boilermakers",
    nickname: "Steam",
    hometown: "Battle Ground, IN",
  },
  {
    id: 142,
    school: "Missouri",
    mascot: "Tigers",
    nickname: "River King",
    hometown: "Arrow Rock, MO",
  },
  {
    id: 130,
    school: "Michigan",
    mascot: "Wolverines",
    nickname: "Lakes",
    hometown: "Dexter, MI",
  },
  {
    id: 2483,
    school: "Oregon",
    mascot: "Ducks",
    nickname: "Rainmaker",
    hometown: "Cottage Grove, OR",
  },
  {
    id: 356,
    school: "Illinois",
    mascot: "Fighting Illini",
    nickname: "John Agapit",
    hometown: "Mahomet, IL",
    upgradePath: "human -> buffalo",
  },
  {
    id: 269,
    school: "Marquette",
    mascot: "Golden Eagles",
    nickname: "Talon",
    hometown: "Cedarburg, WI",
  },
  {
    id: 12,
    school: "Arizona",
    mascot: "Wildcats",
    nickname: "Saguaro",
    hometown: "Tubac, AZ",
    race: "White",
    byline: "Desert explorer and astronomy enthusiast",
  },
  {
    id: 2305,
    school: "Kansas",
    mascot: "Jayhawks",
    nickname: "Wheat King",
    hometown: "Baldwin City, KS",
    race: "White",
    byline: "History major focused on Civil War era Kansas",
  },
  {
    id: 156,
    school: "Creighton",
    mascot: "Bluejays",
    nickname: "Wingspan",
    hometown: "Blair, NE",
    race: "White",
    byline: "Aspiring ornithologist studying bird migration patterns",
  },
  {
    id: 41,
    school: "UConn",
    mascot: "Huskies",
    nickname: "Frost",
    hometown: "Mansfield, CT",
    race: "White",
    byline: "New England native with passion for dog sledding",
  },
  {
    id: 344,
    school: "Mississippi State",
    mascot: "Bulldogs",
    nickname: "Harvest",
    hometown: "Starkville, MS",
    race: "Black",
    byline: "Agricultural science major developing drought-resistant crops",
  },
  {
    id: 145,
    school: "Ole Miss",
    mascot: "Rebels",
    nickname: "Wordsmith",
    hometown: "Water Valley, MS",
    race: "Black",
    byline: "Literature major specializing in Southern Gothic fiction",
  },
  {
    id: 26,
    school: "UCLA",
    mascot: "Bruins",
    nickname: "Director",
    hometown: "Sierra Madre, CA",
    race: "Asian",
    byline: "Film studies major dreaming of Hollywood success",
  },
  {
    id: 167,
    school: "New Mexico",
    mascot: "Lobos",
    nickname: "Terra",
    hometown: "Jemez Springs, NM",
    race: "Hispanic",
    byline: "Environmental science major studying desert ecosystems",
  },
  {
    id: 239,
    school: "Baylor",
    mascot: "Bears",
    nickname: "Waco",
    hometown: "West, TX",
    race: "Black",
    byline:
      "Baptist seminary student studying religious history and basketball",
  },
  {
    id: 277,
    school: "West Virginia",
    mascot: "Mountaineers",
    nickname: "Coal Dust",
    hometown: "Grafton, WV",
    race: "White",
    byline:
      "Mining engineering student with a passion for traditional Appalachian music",
  },
  {
    id: 61,
    school: "Georgia",
    mascot: "Bulldogs",
    nickname: "Peach",
    hometown: "Madison, GA",
    race: "Black",
    byline: "Agriculture major specializing in sustainable farming practices",
  },
  {
    id: 201,
    school: "Oklahoma",
    mascot: "Sooners",
    nickname: "Windrunner",
    hometown: "Purcell, OK",
    race: "Native American",
    byline: "Petroleum engineering student researching renewable energy",
  },
  {
    id: 238,
    school: "Vanderbilt",
    mascot: "Commodores",
    nickname: "Scholar",
    hometown: "Franklin, TN",
    race: "White",
    byline: "Double major in music and biomedical engineering",
  },
  {
    id: 2250,
    school: "Gonzaga",
    mascot: "Bulldogs",
    nickname: "Riverfront",
    hometown: "Cheney, WA",
    race: "White",
    byline: "International relations major focused on Pacific Rim studies",
  },
  {
    id: 2181,
    school: "Drake",
    mascot: "Bulldogs",
    nickname: "Rhyme",
    hometown: "Winterset, IA",
    race: "Black",
    byline: "Communications major with aspirations in music production",
  },
  {
    id: 328,
    school: "Utah State",
    mascot: "Aggies",
    nickname: "Mountain Peak",
    hometown: "Wellsville, UT",
    race: "White",
    byline: "Environmental science major studying high-altitude ecosystems",
  },
];

export const characterById: Record<number, Character> = characters.reduce(
  (acc, character) => {
    acc[character.id] = character;
    return acc;
  },
  {} as Record<number, Character>,
);
